# Generated by Django 5.1.3 on 2025-09-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Количество правильных ответов')),
                ('total_questions', models.IntegerField(verbose_name='Всего вопросов')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время прохождения')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test', verbose_name='Тест')),
            ],
        ),
    ]
