# Generated by Django 5.2.6 on 2025-09-29 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AddField(
            model_name='question',
            name='code_template',
            field=models.TextField(blank=True, help_text='Начальный код для задачи по программированию', null=True, verbose_name='Шаблон кода'),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Ожидаемый вывод программы для проверки', null=True, verbose_name='Ожидаемый результат'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Одиночный выбор'), ('code', 'Задача по программированию')], default='single', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя кандидата'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_spent_minutes',
            field=models.IntegerField(default=0, verbose_name='Затрачено времени (минуты)'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст ответа'),
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('output', models.TextField(blank=True, verbose_name='Вывод программы')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question', verbose_name='Вопрос')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='myapp.testresult', verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Отправленный код',
                'verbose_name_plural': 'Отправленный код',
            },
        ),
    ]
