# Generated by Django 5.2.6 on 2025-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code_template',
            field=models.TextField(blank=True, default='', help_text='Начальный код для задачи по программированию', verbose_name='Шаблон кода'),
        ),
        migrations.AlterField(
            model_name='question',
            name='expected_output',
            field=models.TextField(blank=True, default='', help_text='Ожидаемый вывод программы для проверки', verbose_name='Ожидаемый результат'),
        ),
    ]
