# Generated by Django 5.2.7 on 2025-10-05 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_question_code_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='specialization',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('qa', 'QA'), ('fullstack', 'Fullstack'), ('devops', 'DevOps')], default='backend', max_length=50, verbose_name='Специализация'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('qa', 'QA Engineer'), ('fullstack', 'Fullstack Developer'), ('devops', 'DevOps Engineer')], max_length=50, verbose_name='Специализация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
